{% set version = "0.2.7" %}

package:
  name: ncplot
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/ncplot/ncplot-{{ version }}.tar.gz
  sha256: a878eb1c015d7abb7b77bcca5cc720b1c046dcfcbcad51d35af84d69c1820400

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv


requirements:

  host:
    - python
    - pip
    - numpy
    - setuptools-git

  run:
    - python
    - panel
    - netCDF4
    - hvplot
    - metpy
    - geoviews  >=1.9.4
    - cartopy
    - holoviews
    - bokeh
    - xarray
    - jinja2  <=3.0.3


test:
  imports:
    - ncplot

about:
  home: https://github.com/pmlmodelling/ncplot
  license: GPL-3.0-only
  license_file: LICENSE
  summary: Easy interactive viewing of NetCDF files in Python


extra:
  recipe-maintainers:
    - r4ecology
