{% set version = "0.2.8" %}

package:
  name: ncplot
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/ncplot/ncplot-{{ version }}.tar.gz
  sha256: e12a4860111f75c48e62b7113853bce18c04b5b706699fe568f51b07222d1de3

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv


requirements:

  host:
    - python
    - pip
    - numpy
    - setuptools-git

  run:
    - python
    - panel
    - netCDF4
    - hvplot
    - metpy
    - geoviews  >=1.9.4
    - cartopy
    - holoviews
    - bokeh
    - xarray
    - jinja2  <=3.0.3


test:
  imports:
    - ncplot

about:
  home: https://github.com/pmlmodelling/ncplot
  license: GPL-3.0-only
  license_file: LICENSE
  summary: Easy interactive viewing of NetCDF files in Python


extra:
  recipe-maintainers:
    - r4ecology
