{% set version = "0.0.7" %}

package:
  name: ncplot
  version: {{ version }} 

source:
  url: https://pypi.io/packages/source/n/ncplot/ncplot-{{ version }}.tar.gz 
  sha256: 73e57a9c393fd8e67f8c9e8de85c869b29cb97a820f09879c6d885137b818c9f

build:
  number: 3
  script: {{ PYTHON }} -m pip install . -vv 


requirements:

  host:
    - python
    - pip
    - numpy
    - setuptools-git

  run:
    - python 
    - panel
    - netCDF4
    - hvplot
    - metpy
    - geoviews
    - cartopy
    - holoviews <= 0.13.5
    - bokeh <= 2.2.3
    - xarray <= 0.16.2


test:
  imports:
    - ncplot

about:
  home: https://github.com/pmlmodelling/ncplot 
  license: GPL-3.0-only
  license_file: LICENSE
  summary: "Easy interactive viewing of NetCDF files in Python" 


extra:
  recipe-maintainers:
    - r4ecology
