{% set version = "0.3.4" %}

package:
  name: ncplot
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/ncplot/ncplot-{{ version }}.tar.gz
  sha256: 53ec9bb883c115736ba67bd4e14d35feb9d2e5b03b4831cc327ae0be056fe731

build:

  number: 0

  script: {{ PYTHON }} -m pip install . -vv


requirements:

  host:
    - python
    - pip
    - numpy
    - setuptools-git

  run:
    - python
    - panel
    - netCDF4
    - hvplot
    - metpy
    - holoviews
    - bokeh
    - xarray


test:
  imports:
    - ncplot

about:
  home: https://github.com/pmlmodelling/ncplot
  license: GPL-3.0-only
  license_file: LICENSE
  summary: Easy interactive viewing of NetCDF files in Python


extra:
  recipe-maintainers:
    - robertjwilson
