{% set version = "0.3.13" %}

package:
  name: ncplot
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/n/ncplot/ncplot-{{ version }}.tar.gz
  sha256: 8e81681478a0d5e9f178be3053af3426b00350cee97af3b89bb8543b7f8276e7

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv


requirements:

  host:
    - python >=3.10
    - pip
    - numpy
    - setuptools
    - setuptools-git

  run:
    - python
    - panel
    - netCDF4
    - hvplot
    - metpy
    - holoviews
    - bokeh
    - xarray
    - geoviews >=1.10.0
    - jupyter_bokeh >=3.0.7


test:
  imports:
    - ncplot

about:
  home: https://github.com/pmlmodelling/ncplot
  license: GPL-3.0-only
  license_file: LICENSE
  summary: Easy interactive viewing of NetCDF files in Python


extra:
  recipe-maintainers:
    - robertjwilson
