{% set version = "0.3.8" %}

package:
  name: ncplot
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/ncplot/ncplot-{{ version }}.tar.gz
  sha256: c3403eae70be7e64e29ab17ef934b8316f60a96eeae4a84391c94d79183e4230

build:
  noarch: python
  number: 2
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv


requirements:

  host:
    - python >=3.8
    - pip
    - numpy
    - setuptools-git

  run:
    - python
    - panel
    - netCDF4
    - hvplot
    - metpy
    - holoviews
    - bokeh
    - xarray
    - geoviews >=1.10.0 # [py<312]
    - geoviews-core >=1.10.0 # [py>311]
    - jupyter_bokeh >=3.0.7


test:
  imports:
    - ncplot

about:
  home: https://github.com/pmlmodelling/ncplot
  license: GPL-3.0-only
  license_file: LICENSE
  summary: Easy interactive viewing of NetCDF files in Python


extra:
  recipe-maintainers:
    - robertjwilson
