{% set version = "0.2.4" %}

package:
  name: ncplot
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/ncplot/ncplot-{{ version }}.tar.gz
  sha256: e2df1c63d12683b792cd44a7f0b98dee5a0d358fc2ed1c027daedbbdc1742fde

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv


requirements:

  host:
    - python
    - pip
    - numpy
    - setuptools-git

  run:
    - python
    - panel
    - netCDF4
    - hvplot
    - metpy
    - geoviews
    - cartopy
    - holoviews
    - bokeh
    - xarray


test:
  imports:
    - ncplot

about:
  home: https://github.com/pmlmodelling/ncplot
  license: GPL-3.0-only
  license_file: LICENSE
  summary: Easy interactive viewing of NetCDF files in Python


extra:
  recipe-maintainers:
    - r4ecology
