{% set version = "0.0.9" %}

package:
  name: ncplot
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/ncplot/ncplot-{{ version }}.tar.gz
  sha256: 83943068ceae0197a17c12640fee441969d783943071db317f40e00ef6e2e9c6

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv


requirements:

  host:
    - python
    - pip
    - numpy
    - setuptools-git

  run:
    - python
    - panel
    - netCDF4
    - hvplot
    - metpy
    - geoviews
    - cartopy
    - holoviews <=1.13.5
    - bokeh <=2.2.3
    - xarray <=0.16.2


test:
  imports:
    - ncplot

about:
  home: https://github.com/pmlmodelling/ncplot
  license: GPL-3.0-only
  license_file: LICENSE
  summary: Easy interactive viewing of NetCDF files in Python


extra:
  recipe-maintainers:
    - r4ecology
